[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/gallery-1"
  to = "/gallery-1.html"
  status = 200

[[redirects]]
  from = "/gallery-1.html"
  to = "/gallery-1.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
